### ISSUE TITLE
导入脚本后格式排列异常

### ISSUE THREAD

**Issue by 1zhoubin** [Aobanana-chan/Bilibili_Anime_Space_Cracker#1]
![1694139324207](https://github.com/Aobanana-chan/Bilibili_Anime_Space_Cracker/assets/134057608/54437250-e493-4bbe-b5aa-ed8c8b112eef)

**Comment by 1zhoubin** [comment]
![1694139483359](https://github.com/Aobanana-chan/Bilibili_Anime_Space_Cracker/assets/134057608/11fe1bcc-25c3-4243-b176-cc68410f5ded)

**Comment by Aobanana-chan** [comment]
目前[bilibili-helper](https://github.com/ipcjs/bilibili-helper)已经集成了相似功能。

该项目建于出差番剧账号封锁初期，无相关工具的情况下，供临时使用，最终进入番剧页面还是需要靠[bilibili-helper](https://github.com/ipcjs/bilibili-helper)。从原理上来讲，每次b站对页面有所改动，该脚本就需要有所更新，从维护上来讲，过于繁重。因此在[bilibili-helper](https://github.com/ipcjs/bilibili-helper)有相关功能后，便停止更新。

想要学习该脚本相关原理和制作方法可进入我的博客，里面有较为详细的制作过程。
